/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import { http } from 'msw'

export function deleteThingHandlerResponse204(data?: void) {
  return new Response(JSON.stringify(data), {
    status: 204,
  })
}

export function deleteThingHandler(
  data?: string | number | boolean | null | object | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response | Promise<Response>),
) {
  return http.delete(`/thing`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 204,
    })
  })
}
